// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72KO-lGg-GjSkwtr8hd_DZwRVIkSw9Z8',
    appId: '1:368226906209:android:694ac062ab3b2b34793a20',
    messagingSenderId: '368226906209',
    projectId: 'zinker-4397f',
    storageBucket: 'zinker-4397f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmQz6FSzK5mk-oY2W97Ob7XKuAWdKYBXg',
    appId: '1:368226906209:ios:9c38f1ed1db8162e793a20',
    messagingSenderId: '368226906209',
    projectId: 'zinker-4397f',
    storageBucket: 'zinker-4397f.appspot.com',
    androidClientId: '368226906209-sk3uddeb0ojtckk3cl4hofhf15mg69nn.apps.googleusercontent.com',
    iosClientId: '368226906209-rklirqcv9r7ro6qb2vead5lqvsp4c66s.apps.googleusercontent.com',
    iosBundleId: 'com.example.selfRecipeApp',
  );
}
